services:
  medassistant-db:
    image: ${POSTGRESQL_IMAGE}
    restart: unless-stopped
    hostname: medassistant-db
    container_name: medassistant-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - medassistant-db:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./dumps:/dumps
    networks:
      - compose-net

  medassistant-keycloak-db:
    image: ${POSTGRESQL_IMAGE}
    restart: unless-stopped
    hostname: medassistant-keycloak-db
    container_name: medassistant-keycloak-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - medassistant-keycloak-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - compose-net

  medassistant-keycloak:
    image: keycloak/keycloak:26.7.0
    restart: unless-stopped
    container_name: medassistant-keycloak
    hostname: medassistant-keycloak
    command: start-dev
    ports:
      - "8090:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://medassistant-keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    depends_on:
      - medassistant-keycloak-db
    networks:
      - compose-net

volumes:
  medassistant-db:
  medassistant-keycloak-db:

networks:
  compose-net:
    external: true