services:
  medassistant-db:
    image: ${POSTGRESQL_IMAGE}
    restart: unless-stopped
    hostname: medassistant-db
    container_name: medassistant-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - medassistant-db:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./dumps:/dumps
    networks:
      - compose-net

volumes:
  medassistant-db:

networks:
  compose-net:
    external: true