spring:
  application:
    name: medassistant

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8090/realms/medassistant"